# Generated by Django 5.2.17 on 2026-09-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('horizon_week', models.SmallIntegerField()),
                ('yhat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lo80', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hi80', models.DecimalField(decimal_places=2, max_digits=10)),
                ('model', models.CharField(choices=[('seasonal_naive', 'Seasonal Naive'), ('moving_average', 'Moving Average'), ('sarima', 'Sarima'), ('gru', 'Gru'), ('population', 'Population')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_at', models.DateTimeField()),
                ('git_sha', models.CharField(max_length=40)),
                ('data_sha256', models.CharField(max_length=64)),
                ('params', models.JSONField()),
                ('metrics', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raised_on', models.DateField()),
                ('projected_breach_week', models.DateField()),
                ('projected_doses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('safety_minimum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_weeks', models.SmallIntegerField(default=4)),
                ('safety_buffer', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ref', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('kind', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('receipt', 'Receipt'), ('issue', 'Issue'), ('wastage', 'Wastage'), ('loss', 'Loss'), ('adjustment', 'Adjustment')], max_length=16)),
                ('quantity_doses', models.IntegerField()),
                ('occurred_on', models.DateField()),
                ('is_synthetic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(max_length=32, unique=True)),
                ('first_received', models.DateField()),
                ('expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
