# Generated by Django 5.2.17 on 2026-09-29 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('inventory', '0001_initial'),
        ('passport', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='antigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='passport.antigen'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.forecastrun'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='antigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='passport.antigen'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.forecastrun'),
        ),
        migrations.AddField(
            model_name='stockpolicy',
            name='antigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='passport.antigen'),
        ),
        migrations.AddField(
            model_name='stockpolicy',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='antigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='passport.antigen'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scheduling.outreachsession'),
        ),
        migrations.AddField(
            model_name='vaccinelot',
            name='antigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='passport.antigen'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.vaccinelot'),
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.UniqueConstraint(fields=('run', 'facility', 'antigen', 'week_start'), name='forecast_one_per_run_series_week'),
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.CheckConstraint(condition=models.Q(('horizon_week__gte', 1), ('horizon_week__lte', 4)), name='forecast_horizon_1_4'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['facility', 'status'], name='alert_facility_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'acknowledged', 'resolved'])), name='alert_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='stockpolicy',
            constraint=models.UniqueConstraint(fields=('facility', 'antigen'), name='stockpolicy_one_per_facility_antigen'),
        ),
        migrations.AddConstraint(
            model_name='stockpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('safety_buffer__gte', 0)), name='stockpolicy_buffer_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['facility', 'antigen', 'occurred_on'], name='stocktx_facility_antigen_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['opening_balance', 'receipt', 'issue', 'wastage', 'loss', 'adjustment'])), name='stocktx_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ('opening_balance', 'receipt')), ('quantity_doses__gte', 0)), models.Q(('kind__in', ('issue', 'wastage', 'loss')), ('quantity_doses__lte', 0)), ('kind', 'adjustment'), _connector='OR'), name='stocktx_sign_matches_kind'),
        ),
    ]
