# Generated by Django 5.2.17 on 2026-09-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('keph_level', models.CharField(choices=[('dispensary', 'Dispensary'), ('health_centre', 'Health centre'), ('sub_county_hospital', 'Sub-county hospital')], max_length=24)),
                ('ownership', models.CharField(max_length=24)),
                ('county', models.CharField(max_length=60)),
                ('sub_county', models.CharField(max_length=60)),
                ('is_synthetic', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('keph_level__in', ['dispensary', 'health_centre', 'sub_county_hospital'])), name='facility_keph_level_valid')],
            },
        ),
    ]
