"""Generate F-ERD, F-LDS (PlantUML) and data_dictionary.md from schema.yaml, so the three never drift."""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
HEADER = "' Generated by gen_schema.py from schema.yaml. Do not edit; edit schema.yaml.\n"


def load() -> dict[str, dict]:
    spec = yaml.safe_load((HERE / "schema.yaml").read_text())
    tables = {}
    for app, app_tables in spec["apps"].items():
        for name, table in app_tables.items():
            tables[name] = {**table, "app": app, "sql": f"{app}_{name}", "unique": table.get("unique", [])}
    problems = [
        f"{t}.{col[0]} -> {fk}"
        for t, table in tables.items()
        for col in table["columns"]
        if (fk := foreign_key(col)) and fk not in tables
    ]
    if problems:
        sys.exit("gen_schema: foreign keys to unknown tables: " + ", ".join(problems))
    return tables | {"__views__": spec.get("views", {})}


def foreign_key(col: list) -> str | None:
    for part in str(col[2]).replace(";", " ").split():
        if part.startswith("FK:"):
            return part[3:]
    return None


def nullable(col: list) -> bool:
    return " NULL" in f" {col[2]}".replace("NOT NULL", "")


def key_marks(col: list) -> str:
    flags = str(col[2])
    marks = [m for m in ("PK", "UK") if flags.startswith(m)]
    if foreign_key(col):
        marks.append("FK")
    return ", ".join(marks)


def relationships(tables: dict) -> list[str]:
    lines = []
    for name, table in tables.items():
        if name == "__views__":
            continue
        for col in table["columns"]:
            if target := foreign_key(col):
                arrow = "|o--o{" if nullable(col) else "||--o{"
                lines.append(f"{target} {arrow} {name}")
    return lines


def entity(name: str, table: dict, full: bool) -> list[str]:
    out = [f'entity "{table["sql"]}" as {name} {{']
    for col in table["columns"]:
        marks = key_marks(col)
        if not full and not marks:
            continue
        required = "" if nullable(col) else "* "
        suffix = f" <<{marks}>>" if marks else ""
        typ = f" : {col[1]}" if full else ""
        out.append(f"  {required}{col[0]}{typ}{suffix}")
        if marks == "PK":
            out.append("  --")
    for group in table["unique"]:
        out.append(f"  UK ({', '.join(group)})")
    out.append("}")
    return out


def diagram(tables: dict, name: str, title_comment: str, full: bool) -> str:
    lines = [f"@startuml {name}", HEADER + f"' {title_comment}", "!include style.iuml"]
    lines += ["skinparam linetype ortho", "skinparam nodesep 30", "skinparam ranksep 40", "left to right direction"]
    apps: dict[str, list[str]] = {}
    for tname, table in tables.items():
        if tname != "__views__":
            apps.setdefault(table["app"], []).append(tname)
    for app, names in apps.items():
        lines.append(f'package "{app}" {{')
        for tname in names:
            lines += ["  " + line for line in entity(tname, tables[tname], full)]
        lines.append("}")
    lines += relationships(tables)
    lines.append("@enduml")
    return "\n".join(lines) + "\n"


def dictionary(tables: dict) -> str:
    out = [
        "# Data dictionary (logical schema)",
        "",
        "Generated by `docs/diagrams/gen_schema.py` from `schema.yaml`; do not edit by hand. "
        "Every table also has `created_at` and `updated_at` (timestamptz, NOT NULL, set by the application). "
        "Columns are NOT NULL unless marked NULL. Source is the column of a run's `app/*.csv` that the "
        "Phase 3 loader maps into the table; `-` means the system creates the value. Nothing from `truth/` "
        "is stored.",
        "",
        "## CSV to table mapping",
        "",
        "| CSV (`app/`) | Table |",
        "|---|---|",
    ]
    for table in tables.values():
        if isinstance(table, dict) and table.get("csv"):
            out.append(f"| `{table['csv']}` | `{table['sql']}` |")
    for tname, table in tables.items():
        if tname == "__views__":
            continue
        out += ["", f"## `{table['sql']}`", "", table["purpose"], ""]
        out += ["| Column | Type | Keys and constraints | Source |", "|---|---|---|---|"]
        for col in table["columns"]:
            constraints = str(col[2] or "").replace("|", "\\|")
            out.append(f"| `{col[0]}` | {col[1]} | {constraints} | {col[3]} |")
        for group in table["unique"]:
            out.append(f"| (unique) |  | UNIQUE ({', '.join(group)}) |  |")
    out += ["", "## Views", ""]
    out += [f"- `{name}`: {sql}" for name, sql in tables["__views__"].items()]
    return "\n".join(out) + "\n"


def main() -> None:
    tables = load()
    (HERE / "F-ERD_entity_relationship.puml").write_text(
        diagram(tables, "F-ERD_entity_relationship", "F-ERD: entities, keys and relationships", False)
    )
    (HERE / "F-LDS_logical_schema.puml").write_text(
        diagram(tables, "F-LDS_logical_schema", "F-LDS: logical database schema, all columns", True)
    )
    (HERE / "data_dictionary.md").write_text(dictionary(tables))
    print(f"gen_schema: {len(tables) - 1} tables -> F-ERD, F-LDS, data_dictionary.md")


if __name__ == "__main__":
    main()
