# Generated by Django 5.2.17 on 2026-09-29 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('healthcare_worker', 'Healthcare worker'), ('facility_manager', 'Facility manager'), ('system_admin', 'System administrator')], max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('failed_logins', models.SmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('read', 'Read'), ('export', 'Export'), ('login', 'Login'), ('login_failed', 'Login Failed'), ('lockout', 'Lockout'), ('logout', 'Logout')], max_length=32)),
                ('entity', models.CharField(max_length=48)),
                ('entity_id', models.CharField(max_length=64)),
                ('cross_facility', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='facilities.facility')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['healthcare_worker', 'facility_manager', 'system_admin'])), name='user_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('facility__isnull', True), ('role', 'system_admin')), models.Q(models.Q(('role', 'system_admin'), _negated=True), ('facility__isnull', False)), _connector='OR'), name='user_facility_matches_role'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['facility', 'at'], name='audit_facility_at_idx'),
        ),
    ]
