# Generated by Django 5.2.17 on 2026-09-29 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dose_code', models.CharField(max_length=12, unique=True)),
                ('dose_number', models.SmallIntegerField()),
                ('contact', models.CharField(max_length=8)),
                ('recommended_age_days', models.IntegerField()),
                ('min_age_days', models.IntegerField()),
                ('max_age_days', models.IntegerField()),
                ('min_interval_days', models.IntegerField()),
            ],
            options={
                'ordering': ['recommended_age_days', 'dose_code'],
            },
        ),
        migrations.CreateModel(
            name='Antigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('doses_per_vial', models.SmallIntegerField()),
                ('open_vial_policy', models.BooleanField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('doses_per_vial__gte', 1)), name='antigen_doses_per_vial_positive')],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_id', models.CharField(max_length=32, unique=True)),
                ('source_ref', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('given_name', models.CharField(max_length=80)),
                ('family_name', models.CharField(max_length=80)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('caregiver_name', models.CharField(max_length=120)),
                ('registered_on', models.DateField()),
                ('is_synthetic', models.BooleanField(default=False)),
                ('registration_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_children', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='ImmunizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ref', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('given_on', models.DateField()),
                ('is_synthetic', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='passport.child')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='facilities.facility')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.vaccinelot')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
