# Generated by Django 5.2.17 on 2026-09-29 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passport', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationevent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='scheduling.outreachsession'),
        ),
        migrations.AddField(
            model_name='scheduledose',
            name='antigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doses', to='passport.antigen'),
        ),
        migrations.AddField(
            model_name='immunizationevent',
            name='schedule_dose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='passport.scheduledose'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['family_name', 'date_of_birth'], name='child_name_dob_idx'),
        ),
        migrations.AddConstraint(
            model_name='child',
            constraint=models.CheckConstraint(condition=models.Q(('sex__in', ['F', 'M'])), name='child_sex_valid'),
        ),
        migrations.AddConstraint(
            model_name='scheduledose',
            constraint=models.CheckConstraint(condition=models.Q(('min_age_days__lte', models.F('recommended_age_days')), ('recommended_age_days__lte', models.F('max_age_days'))), name='scheduledose_age_window_ordered'),
        ),
        migrations.AddIndex(
            model_name='immunizationevent',
            index=models.Index(fields=['facility', 'given_on'], name='event_facility_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='immunizationevent',
            constraint=models.UniqueConstraint(fields=('child', 'schedule_dose'), name='event_one_per_child_dose'),
        ),
    ]
