# Generated by Django 5.2.17 on 2026-09-29 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ref', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('fixed', 'Fixed'), ('outreach', 'Outreach')], max_length=8)),
                ('location_name', models.CharField(max_length=120)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('held', 'Held')], default='planned', max_length=8)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended', models.BooleanField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='passport.child')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='scheduling.outreachsession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority_rank', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='passport.child')),
                ('schedule_dose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='passport.scheduledose')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='scheduling.outreachsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='outreachsession',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['fixed', 'outreach'])), name='session_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='outreachsession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'held'])), name='session_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='sessionattendance',
            constraint=models.UniqueConstraint(fields=('session', 'child'), name='attendance_one_per_session_child'),
        ),
        migrations.AddConstraint(
            model_name='sessionplanitem',
            constraint=models.UniqueConstraint(fields=('session', 'child', 'schedule_dose'), name='planitem_one_per_session_child_dose'),
        ),
    ]
